# This file is AUTO GENERATED by parser_generator.py - DO NOT EDIT!
from obj_ids import ID
from parser_utils import *

def parse_compound_obj(obj_id, data, parse_obj, parse_primitive_obj):

	if False: # just to get the elif chain started...
		pass

	elif obj_id == ID.ARExpansionGoodsDef:
		obj = {}
		obj["id"] = unpackex("h", data)
		obj["type"] = unpackex("h", data)
		obj["price"] = parse_obj(data)
		return ("ARExpansionGoodsDef", obj)

	elif obj_id == ID.AbilityParam:
		obj = {}
		obj["type"] = unpackex("i", data)
		obj["values"] = parse_obj(data)
		obj["secs"] = unpackex("i", data)
		return ("AbilityParam", obj)

	elif obj_id == ID.AssistInfo:
		obj = {}
		obj["aid"] = unpackex("d", data)
		obj["encodedUid"] = unpackex("i", data)
		obj["playerName"] = parseUTF(data)
		obj["playerRank"] = unpackex("i", data)
		obj["kitchenwareType"] = unpackex("i", data)
		obj["gudetamaId"] = unpackex("i", data)
		obj["finishTimeSecs"] = unpackex("i", data)
		obj["usefulId"] = unpackex("i", data)
		obj["assistTimeSecs"] = unpackex("i", data)
		obj["avatar"] = unpackex("i", data)
		obj["snsProfileImage"] = parse_obj(data)
		obj["snsType"] = unpackex("b", data)
		return ("AssistInfo", obj)

	elif obj_id == ID.AvatarData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["acquired"] = unpackex("b", data)
		obj["available"] = unpackex("b", data)
		return ("AvatarData", obj)

	elif obj_id == ID.AvatarDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["conditionDesc"] = parseUTF(data)
		obj["price"] = parse_obj(data)
		obj["isNew"] = unpackex("b", data)
		return ("AvatarDef", obj)

	elif obj_id == ID.AvatarInfo:
		obj = {}
		obj["updateAvatars"] = parse_obj(data)
		obj["removeAvatarIds"] = parse_obj(data)
		return ("AvatarInfo", obj)

	elif obj_id == ID.CheckedMessageInfo:
		obj = {}
		obj["seq"] = parse_obj(data)
		obj["type"] = unpackex("i", data)
		obj["target"] = unpackex("i", data)
		return ("CheckedMessageInfo", obj)

	elif obj_id == ID.ComicDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrcs"] = parse_obj(data)
		obj["comicSpine"] = parse_obj(data)
		return ("ComicDef", obj)

	elif obj_id == ID.ComicSpineDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["spainMap"] = parse_primitive_obj(ID(8), data)
		obj["spainAnimeMap"] = parse_primitive_obj(ID(8), data)
		obj["spainScaleMap"] = parse_primitive_obj(ID(8), data)
		obj["spainDelayMap"] = parse_primitive_obj(ID(8), data)
		return ("ComicSpineDef", obj)

	elif obj_id == ID.CommentDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		return ("CommentDef", obj)

	elif obj_id == ID.CommonConstants:
		obj = {}
		return ("CommonConstants", obj)

	elif obj_id == ID.ConvertParam:
		obj = {}
		obj["originalItem"] = parse_obj(data)
		obj["convertedItem"] = parse_obj(data)
		obj["convertedParam"] = parse_obj(data)
		obj["kind"] = unpackex("i", data)
		obj["id"] = unpackex("i", data)
		obj["num"] = unpackex("i", data)
		return ("ConvertParam", obj)

	elif obj_id == ID.CupGachaData:
		obj = {}
		obj["cookIndex"] = unpackex("b", data)
		obj["cupGachaIds"] = parse_obj(data)
		obj["restSec"] = unpackex("i", data)
		obj["showAdNum"] = unpackex("b", data)
		return ("CupGachaData", obj)

	elif obj_id == ID.CupGachaDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["rarity"] = unpackex("b", data)
		obj["prizes"] = parse_obj(data)
		obj["oddses"] = parse_obj(data)
		obj["cookMin"] = unpackex("i", data)
		obj["price"] = parse_obj(data)
		obj["isNew"] = unpackex("b", data)
		obj["conditionDesc"] = parseUTF(data)
		obj["sortIndex"] = unpackex("i", data)
		obj["enableCountryFlags"] = parse_obj(data)
		obj["missionCommonID"] = unpackex("i", data)
		return ("CupGachaDef", obj)

	elif obj_id == ID.CupGachaResult:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["results"] = parse_primitive_obj(ID(9), data)
		return ("CupGachaResult", obj)

	elif obj_id == ID.DecorationData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["acquired"] = unpackex("b", data)
		obj["available"] = unpackex("b", data)
		return ("DecorationData", obj)

	elif obj_id == ID.DecorationDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["conditionDesc"] = parseUTF(data)
		obj["price"] = parse_obj(data)
		obj["isNew"] = unpackex("b", data)
		return ("DecorationDef", obj)

	elif obj_id == ID.DecorationInfo:
		obj = {}
		obj["updateDecorations"] = parse_obj(data)
		obj["removeDecorationIds"] = parse_obj(data)
		return ("DecorationInfo", obj)

	elif obj_id == ID.DeliverPointTableDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["gudePointMap"] = parse_primitive_obj(ID(7), data)
		return ("DeliverPointTableDef", obj)

	elif obj_id == ID.DelusionDef:
		obj = {}
		obj["param"] = parse_obj(data)
		return ("DelusionDef", obj)

	elif obj_id == ID.DelusionParam:
		obj = {}
		obj["pastMinutes"] = unpackex("i", data)
		return ("DelusionParam", obj)

	elif obj_id == ID.DictDef:
		obj = {}
		obj["uitext"] = parse_primitive_obj(ID(8), data)
		obj["message"] = parse_primitive_obj(ID(8), data)
		obj["textplain"] = parse_primitive_obj(ID(8), data)
		obj["others"] = parse_primitive_obj(ID(8), data)
		obj["voice"] = parse_primitive_obj(ID(8), data)
		obj["guide"] = parse_primitive_obj(ID(8), data)
		obj["inviteRewardRobos"] = parse_obj(data)
		obj["guideLocalizeImages"] = parse_obj(data)
		obj["noticeLocalizeImages"] = parse_obj(data)
		obj["notice"] = parse_obj(data)
		obj["hintNum"] = unpackex("i", data)
		return ("DictDef", obj)

	elif obj_id == ID.EventData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["endRestTimeSecs"] = unpackex("i", data)
		obj["background"] = parseUTF(data)
		obj["buttonImage"] = parseUTF(data)
		obj["title"] = parseUTF(data)
		obj["message"] = parseUTF(data)
		obj["url"] = parseUTF(data)
		obj["decorationId"] = unpackex("i", data)
		obj["endTallyRestTimeSecs"] = unpackex("i", data)
		obj["rankingId"] = unpackex("i", data)
		obj["noticeIconRsrc"] = unpackex("i", data)
		obj["gudetamaIds"] = parse_obj(data)
		obj["chBGM"] = parse_obj(data)
		obj["rentalDecorations"] = parse_obj(data)
		obj["noticeTextKey"] = parseUTF(data)
		obj["attendable"] = unpackex("b", data)
		return ("EventData", obj)

	elif obj_id == ID.EventPreset:
		obj = {}
		return ("EventPreset", obj)

	elif obj_id == ID.FeatureDef:
		obj = {}
		obj["paramMap"] = parse_primitive_obj(ID(7), data)
		return ("FeatureDef", obj)

	elif obj_id == ID.FeatureParam:
		obj = {}
		obj["type"] = unpackex("i", data)
		obj["value"] = unpackex("i", data)
		return ("FeatureParam", obj)

	elif obj_id == ID.FileInfoDef:
		obj = {}
		obj["path"] = parseUTF(data)
		obj["size"] = unpackex("i", data)
		obj["hash"] = unpackex("i", data)
		obj["hasLocale"] = unpackex("b", data)
		return ("FileInfoDef", obj)

	elif obj_id == ID.FirstLoginInfo:
		obj = {}
		obj["name"] = parseUTF(data)
		obj["gender"] = unpackex("i", data)
		obj["area"] = unpackex("i", data)
		obj["timeZone"] = parseUTF(data)
		obj["locale"] = parseUTF(data)
		obj["deckIndex"] = unpackex("i", data)
		obj["comment"] = unpackex("i", data)
		obj["avatar"] = unpackex("i", data)
		return ("FirstLoginInfo", obj)

	elif obj_id == ID.FriendAssistResult:
		obj = {}
		obj["userRoomInfo"] = parse_obj(data)
		obj["lastFriendly"] = unpackex("i", data)
		obj["addFriendly"] = unpackex("i", data)
		obj["lastFriendlyLevel"] = unpackex("i", data)
		return ("FriendAssistResult", obj)

	elif obj_id == ID.FriendInfo:
		obj = {}
		obj["friendlyData"] = parse_obj(data)
		obj["wantedGudetamas"] = parse_obj(data)
		obj["friendPresentLogDiff"] = parse_obj(data)
		obj["lastFriendlyLevel"] = unpackex("i", data)
		return ("FriendInfo", obj)

	elif obj_id == ID.FriendPresentResult:
		obj = {}
		obj["friendlyData"] = parse_obj(data)
		obj["consumedGudetama"] = parse_obj(data)
		obj["lastFriendly"] = unpackex("i", data)
		obj["addFriendly"] = unpackex("i", data)
		obj["friendPresentLogDiff"] = parse_obj(data)
		obj["lastFriendlyLevel"] = unpackex("i", data)
		obj["deliveredEventIds"] = parse_obj(data)
		return ("FriendPresentResult", obj)

	elif obj_id == ID.FriendlyData:
		obj = {}
		obj["encodedUid"] = unpackex("i", data)
		obj["friendly"] = unpackex("i", data)
		obj["friendlyLevel"] = unpackex("i", data)
		return ("FriendlyData", obj)

	elif obj_id == ID.FriendlyDef:
		obj = {}
		obj["params"] = parse_obj(data)
		obj["heartBorders"] = parse_obj(data)
		return ("FriendlyDef", obj)

	elif obj_id == ID.FriendlyParam:
		obj = {}
		obj["index"] = unpackex("i", data)
		obj["max"] = unpackex("i", data)
		obj["rewards"] = parse_obj(data)
		return ("FriendlyParam", obj)

	elif obj_id == ID.GachaData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["existsPickup"] = unpackex("b", data)
		return ("GachaData", obj)

	elif obj_id == ID.GachaDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["sortIndex"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["lineupDesc"] = parseUTF(data)
		obj["prices"] = parse_obj(data)
		obj["numFree"] = unpackex("i", data)
		obj["numOnceMore"] = unpackex("i", data)
		obj["screeningItems"] = parse_obj(data)
		obj["ratesAtKind"] = parse_obj(data)
		obj["hasRareStamp"] = unpackex("b", data)
		obj["gachaLineupPrioritizedKinds"] = parse_obj(data)
		return ("GachaDef", obj)

	elif obj_id == ID.GachaPriceDef:
		obj = {}
		obj["num"] = unpackex("i", data)
		obj["prices"] = parse_obj(data)
		obj["numDaily"] = unpackex("i", data)
		obj["enabledCollect"] = unpackex("b", data)
		return ("GachaPriceDef", obj)

	elif obj_id == ID.GachaResult:
		obj = {}
		obj["userGachaData"] = parse_obj(data)
		obj["items"] = parse_obj(data)
		obj["params"] = parse_obj(data)
		obj["convertedItems"] = parse_obj(data)
		obj["rarities"] = parse_obj(data)
		obj["worthFlags"] = parse_obj(data)
		obj["onceMore"] = unpackex("b", data)
		obj["useItem"] = parse_obj(data)
		return ("GachaResult", obj)

	elif obj_id == ID.GameDef:
		obj = {}
		obj["version"] = unpackex("i", data)
		obj["dict"] = parse_obj(data)
		obj["initDict"] = parse_obj(data)
		obj["rule"] = parse_obj(data)
		obj["screening"] = parse_obj(data)
		obj["kitchenwareMap"] = parse_primitive_obj(ID(7), data)
		obj["recipeNoteMap"] = parse_primitive_obj(ID(7), data)
		obj["gudetamaMap"] = parse_primitive_obj(ID(7), data)
		obj["voiceMap"] = parse_primitive_obj(ID(7), data)
		obj["gachaMap"] = parse_primitive_obj(ID(7), data)
		obj["usefulMap"] = parse_primitive_obj(ID(7), data)
		obj["decorationMap"] = parse_primitive_obj(ID(7), data)
		obj["utensilMap"] = parse_primitive_obj(ID(7), data)
		obj["stampMap"] = parse_primitive_obj(ID(7), data)
		obj["avatarMap"] = parse_primitive_obj(ID(7), data)
		obj["missionMap"] = parse_primitive_obj(ID(7), data)
		obj["touch"] = parse_obj(data)
		obj["delusion"] = parse_obj(data)
		obj["feature"] = parse_obj(data)
		obj["friendly"] = parse_obj(data)
		obj["videoAdReward"] = parse_obj(data)
		obj["linkageMap"] = parse_primitive_obj(ID(7), data)
		obj["questionMap"] = parse_primitive_obj(ID(7), data)
		obj["arExpansionGoodsMap"] = parse_primitive_obj(ID(7), data)
		obj["hideGudeMap"] = parse_primitive_obj(ID(7), data)
		obj["commentMap"] = parse_primitive_obj(ID(7), data)
		obj["promotionVideoMap"] = parse_primitive_obj(ID(7), data)
		obj["identifiedPresentMap"] = parse_primitive_obj(ID(7), data)
		obj["shareBonusMap"] = parse_primitive_obj(ID(7), data)
		obj["quizGenreIdMax"] = unpackex("i", data)
		obj["battleItemIdMax"] = unpackex("i", data)
		obj["metalShopTable"] = parse_primitive_obj(ID(7), data)
		obj["monthlyPremiumBonusTable"] = parse_primitive_obj(ID(7), data)
		obj["guideTalkTable"] = parse_primitive_obj(ID(7), data)
		obj["rankingMap"] = parse_primitive_obj(ID(7), data)
		obj["rankingRewardMap"] = parse_primitive_obj(ID(7), data)
		obj["fileInfos"] = parse_obj(data)
		obj["locale"] = parseUTF(data)
		obj["resourceUrl"] = parseUTF(data)
		obj["purchasePresentTable"] = parse_primitive_obj(ID(7), data)
		obj["bannerTable"] = parse_primitive_obj(ID(7), data)
		obj["interTable"] = parse_primitive_obj(ID(7), data)
		obj["deliverPointTableMap"] = parse_primitive_obj(ID(7), data)
		obj["setItemMap"] = parse_primitive_obj(ID(7), data)
		obj["comicMap"] = parse_primitive_obj(ID(7), data)
		obj["onlyShowMap"] = parse_primitive_obj(ID(7), data)
		obj["cupGachaMap"] = parse_primitive_obj(ID(7), data)
		obj["homeExpansionGoodsMap"] = parse_primitive_obj(ID(7), data)
		obj["homeStampSettingMap"] = parse_primitive_obj(ID(7), data)
		obj["kitchenwareConditionMap"] = parse_primitive_obj(ID(7), data)
		obj["helperSettingMap"] = parse_primitive_obj(ID(7), data)
		obj["helperComicDef"] = parse_obj(data)
		return ("GameDef", obj)

	elif obj_id == ID.GetItemResult:
		obj = {}
		obj["item"] = parse_obj(data)
		obj["param"] = parse_obj(data)
		obj["toMail"] = unpackex("b", data)
		return ("GetItemResult", obj)

	elif obj_id == ID.GudetamaConstants:
		obj = {}
		return ("GudetamaConstants", obj)

	elif obj_id == ID.GudetamaData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["count"] = unpackex("h", data)
		obj["num"] = unpackex("h", data)
		obj["unlockedVoiceIndex"] = unpackex("b", data)
		obj["available"] = unpackex("b", data)
		obj["unlocked"] = unpackex("b", data)
		obj["alreadyChallenge"] = unpackex("b", data)
		obj["cookedHappening"] = unpackex("b", data)
		obj["cookedFailure"] = unpackex("b", data)
		obj["targetValue"] = unpackex("i", data)
		obj["currentValue"] = unpackex("i", data)
		obj["currentTarget"] = unpackex("i", data)
		return ("GudetamaData", obj)

	elif obj_id == ID.GudetamaDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["uncountable"] = unpackex("b", data)
		obj["disabledSpine"] = unpackex("b", data)
		obj["imageOffsX"] = unpackex("i", data)
		obj["imageOffsY"] = unpackex("i", data)
		obj["kitchenwareId"] = unpackex("i", data)
		obj["recipeNoteId"] = unpackex("i", data)
		obj["type"] = unpackex("b", data)
		obj["number"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["wrappedName"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["cost"] = unpackex("i", data)
		obj["reward"] = unpackex("i", data)
		obj["rarity"] = unpackex("b", data)
		obj["category"] = unpackex("b", data)
		obj["country"] = unpackex("b", data)
		obj["area"] = unpackex("h", data)
		obj["voices"] = parse_obj(data)
		obj["voiceType"] = unpackex("b", data)
		obj["dropAnime"] = unpackex("i", data)
		obj["dish"] = unpackex("b", data)
		obj["materials"] = unpackex("i", data)
		obj["conditionDesc"] = parseUTF(data)
		obj["roulettes"] = parse_obj(data)
		obj["rouletteTimePerRound"] = unpackex("i", data)
		obj["cookingResultType"] = unpackex("i", data)
		obj["isGacha"] = unpackex("b", data)
		obj["requiredGudetamas"] = parse_obj(data)
		obj["touchTextParams"] = parse_obj(data)
		obj["rubTextParams"] = parse_obj(data)
		obj["isCup"] = unpackex("b", data)
		obj["targetType"] = unpackex("i", data)
		obj["targetId"] = unpackex("i", data)
		return ("GudetamaDef", obj)

	elif obj_id == ID.GuideTalkDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["paragraph"] = parse_obj(data)
		obj["cannotSkip"] = unpackex("b", data)
		return ("GuideTalkDef", obj)

	elif obj_id == ID.GuideTalkParagraphParam:
		obj = {}
		obj["sentences"] = parse_obj(data)
		return ("GuideTalkParagraphParam", obj)

	elif obj_id == ID.GuideTalkSentenceParam:
		obj = {}
		obj["word"] = unpackex("b", data)
		obj["event"] = unpackex("b", data)
		obj["paramInt"] = unpackex("i", data)
		obj["paramStr"] = parseUTF(data)
		obj["waitTime"] = unpackex("f", data)
		obj["forceTime"] = unpackex("f", data)
		obj["nextWordsConnect"] = unpackex("b", data)
		obj["forceWordsFinish"] = unpackex("b", data)
		return ("GuideTalkSentenceParam", obj)

	elif obj_id == ID.HelperCharaDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["showRate"] = unpackex("i", data)
		obj["massages"] = parse_primitive_obj(ID(8), data)
		obj["massagePosIndex"] = parse_primitive_obj(ID(8), data)
		obj["voices"] = parse_primitive_obj(ID(8), data)
		obj["fixHelperPosX"] = unpackex("i", data)
		return ("HelperCharaDef", obj)

	elif obj_id == ID.HideGudetamaDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		return ("HideGudetamaDef", obj)

	elif obj_id == ID.HomeDecoData:
		obj = {}
		obj["stampId"] = unpackex("i", data)
		obj["index"] = unpackex("h", data)
		obj["x"] = unpackex("d", data)
		obj["y"] = unpackex("d", data)
		obj["rotation"] = unpackex("f", data)
		obj["scale"] = unpackex("f", data)
		obj["screenPosRateX"] = unpackex("f", data)
		obj["screenPosRateY"] = unpackex("f", data)
		obj["isSpain"] = unpackex("b", data)
		return ("HomeDecoData", obj)

	elif obj_id == ID.HomeExpansionGoodsDef:
		obj = {}
		obj["id"] = unpackex("h", data)
		obj["price"] = parse_obj(data)
		return ("HomeExpansionGoodsDef", obj)

	elif obj_id == ID.HomeStampSettingDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["animationName"] = parseUTF(data)
		obj["slotName"] = parseUTF(data)
		obj["attachmentName"] = parseUTF(data)
		obj["loop"] = unpackex("b", data)
		obj["touchSetting"] = parse_obj(data)
		obj["music"] = parseUTF(data)
		obj["sound"] = parseUTF(data)
		return ("HomeStampSettingDef", obj)

	elif obj_id == ID.IdentifiedPresentDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["limit"] = unpackex("i", data)
		obj["url"] = parseUTF(data)
		return ("IdentifiedPresentDef", obj)

	elif obj_id == ID.InitDictDef:
		obj = {}
		obj["others"] = parse_primitive_obj(ID(8), data)
		obj["uitext"] = parse_primitive_obj(ID(8), data)
		return ("InitDictDef", obj)

	elif obj_id == ID.ItemParam:
		obj = {}
		obj["kind"] = unpackex("i", data)
		obj["id"] = unpackex("i", data)
		obj["num"] = unpackex("i", data)
		return ("ItemParam", obj)

	elif obj_id == ID.KitchenwareData:
		obj = {}
		obj["type"] = unpackex("i", data)
		obj["paramMap"] = parse_primitive_obj(ID(7), data)
		obj["recipeNoteId"] = unpackex("i", data)
		obj["gudetamaId"] = unpackex("i", data)
		obj["restTimeSecs"] = unpackex("i", data)
		obj["assistUsefulIds"] = parse_obj(data)
		obj["assistEncodedUids"] = parse_obj(data)
		obj["target"] = unpackex("i", data)
		return ("KitchenwareData", obj)

	elif obj_id == ID.KitchenwareDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["type"] = unpackex("i", data)
		obj["grade"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["recipeNoteIds"] = parse_obj(data)
		obj["conditionDesc"] = parseUTF(data)
		obj["existsImage"] = unpackex("b", data)
		obj["bgPos"] = parse_obj(data)
		obj["materialLayer"] = unpackex("i", data)
		obj["eventIds"] = parse_obj(data)
		return ("KitchenwareDef", obj)

	elif obj_id == ID.KitchenwareInfo:
		obj = {}
		obj["unavailableRecipeNoteIds"] = parse_obj(data)
		obj["unavailableGudetamaIds"] = parse_obj(data)
		return ("KitchenwareInfo", obj)

	elif obj_id == ID.KitchenwareParam:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["available"] = unpackex("b", data)
		return ("KitchenwareParam", obj)

	elif obj_id == ID.LinearTable:
		obj = {}
		obj["offset"] = unpackex("f", data)
		obj["rate"] = unpackex("f", data)
		obj["indexOffset"] = unpackex("i", data)
		obj["indexes"] = parse_obj(data)
		obj["values"] = parse_obj(data)
		return ("LinearTable", obj)

	elif obj_id == ID.LinkageData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["code"] = parseUTF(data)
		obj["notified"] = unpackex("b", data)
		return ("LinkageData", obj)

	elif obj_id == ID.LinkageDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["title"] = parseUTF(data)
		obj["name"] = parseUTF(data)
		obj["linkTitle"] = parseUTF(data)
		obj["linkMessage"] = parseUTF(data)
		obj["linkUrl"] = parse_obj(data)
		obj["conditionDesc"] = parseUTF(data)
		return ("LinkageDef", obj)

	elif obj_id == ID.MailPresentResult:
		obj = {}
		obj["items"] = parse_obj(data)
		obj["params"] = parse_obj(data)
		return ("MailPresentResult", obj)

	elif obj_id == ID.MetalShopDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["items"] = parse_obj(data)
		return ("MetalShopDef", obj)

	elif obj_id == ID.MetalShopItemDef:
		obj = {}
		obj["key"] = unpackex("i", data)
		obj["rsrc"] = unpackex("b", data)
		obj["value"] = unpackex("i", data)
		obj["bonus"] = unpackex("i", data)
		obj["campaign"] = unpackex("i", data)
		obj["price"] = unpackex("i", data)
		obj["product_id"] = parseUTF(data)
		obj["items"] = parse_obj(data)
		obj["limit"] = unpackex("i", data)
		obj["overlap"] = parse_obj(data)
		obj["ranklimit"] = unpackex("i", data)
		obj["applimit"] = unpackex("i", data)
		obj["info"] = unpackex("i", data)
		return ("MetalShopItemDef", obj)

	elif obj_id == ID.MissionConstants:
		obj = {}
		return ("MissionConstants", obj)

	elif obj_id == ID.MissionData:
		obj = {}
		obj["key"] = unpackex("i", data)
		obj["param"] = parse_obj(data)
		obj["currentValue"] = unpackex("h", data)
		obj["id"] = unpackex("h", data)
		return ("MissionData", obj)

	elif obj_id == ID.MissionDef:
		obj = {}
		obj["id"] = unpackex("h", data)
		obj["number"] = unpackex("i", data)
		obj["counterType"] = unpackex("i", data)
		obj["eventId"] = unpackex("i", data)
		obj["eventTypeFlags"] = unpackex("i", data)
		obj["enableCountryFlags"] = parse_obj(data)
		return ("MissionDef", obj)

	elif obj_id == ID.MissionParam:
		obj = {}
		obj["number"] = unpackex("i", data)
		obj["type"] = unpackex("b", data)
		obj["category"] = unpackex("b", data)
		obj["guide"] = unpackex("h", data)
		obj["goalValue"] = unpackex("h", data)
		obj["finishSecs"] = unpackex("i", data)
		obj["targetDescKey"] = parseUTF(data)
		obj["titleKey"] = parseUTF(data)
		obj["nextTitleKey"] = parseUTF(data)
		obj["rewards"] = parse_obj(data)
		obj["titleParam"] = parse_obj(data)
		obj["counterType"] = unpackex("i", data)
		return ("MissionParam", obj)

	elif obj_id == ID.MonthlyPremiumBonusDef:
		obj = {}
		obj["id"] = unpackex("h", data)
		obj["validDays"] = unpackex("h", data)
		obj["item"] = parse_obj(data)
		obj["bonusItems"] = parse_obj(data)
		return ("MonthlyPremiumBonusDef", obj)

	elif obj_id == ID.NoticeFlagData:
		obj = {}
		obj["noticeFlags"] = parse_obj(data)
		obj["tutorialProgress"] = unpackex("i", data)
		obj["bitFlags"] = unpackex("i", data)
		return ("NoticeFlagData", obj)

	elif obj_id == ID.OnlyShowItemDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		return ("OnlyShowItemDef", obj)

	elif obj_id == ID.Packet:
		obj = {}
		obj["type"] = unpackex("i", data)
		obj["time"] = unpackex("i", data)
		obj["payloadInt"] = parse_obj(data)
		obj["payloadObj0"] = parse_obj(data)
		obj["payloadObj1"] = parse_obj(data)
		obj["payloadExtra"] = parse_obj(data)
		obj["sequence"] = unpackex("h", data)
		obj["relogin"] = unpackex("b", data)
		return ("Packet", obj)

	elif obj_id == ID.PossibleRouletteParam:
		obj = {}
		obj["type"] = unpackex("b", data)
		obj["percent"] = unpackex("i", data)
		return ("PossibleRouletteParam", obj)

	elif obj_id == ID.PresentLogData:
		obj = {}
		obj["encodedUid"] = unpackex("i", data)
		obj["playerRank"] = unpackex("i", data)
		obj["playerName"] = parseUTF(data)
		obj["avatar"] = unpackex("i", data)
		obj["itemId"] = unpackex("i", data)
		obj["itemNum"] = unpackex("i", data)
		obj["time"] = unpackex("i", data)
		obj["snsProfileImage"] = parse_obj(data)
		obj["snsType"] = unpackex("b", data)
		return ("PresentLogData", obj)

	elif obj_id == ID.PromotionBannerSettingDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["allowCountriyCodes"] = parse_obj(data)
		obj["allowCountryLocales"] = parse_obj(data)
		obj["bannerID"] = parseUTF(data)
		obj["visible"] = unpackex("b", data)
		obj["startTimeSecs"] = unpackex("i", data)
		obj["limitTimeSecs"] = unpackex("i", data)
		obj["endTimeStr"] = parseUTF(data)
		obj["browserType"] = unpackex("b", data)
		obj["webURL"] = parse_obj(data)
		return ("PromotionBannerSettingDef", obj)

	elif obj_id == ID.PromotionInterstitialSettingDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["allowCountriyCodes"] = parse_obj(data)
		obj["allowCountryLocales"] = parse_obj(data)
		obj["imageIDs"] = parse_obj(data)
		obj["visible"] = unpackex("b", data)
		obj["startTimeSecs"] = unpackex("i", data)
		obj["limitTimeSecs"] = unpackex("i", data)
		obj["endTimeStr"] = parseUTF(data)
		obj["browserType"] = unpackex("b", data)
		obj["webURL"] = parse_obj(data)
		obj["rate"] = unpackex("i", data)
		obj["intervalSec"] = unpackex("i", data)
		return ("PromotionInterstitialSettingDef", obj)

	elif obj_id == ID.PromotionVideoDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["movie"] = unpackex("i", data)
		obj["endcard"] = unpackex("i", data)
		obj["landscape"] = unpackex("b", data)
		obj["urlApple"] = parseUTF(data)
		obj["urlGoogle"] = parseUTF(data)
		obj["link"] = parseUTF(data)
		obj["locales"] = parse_obj(data)
		return ("PromotionVideoDef", obj)

	elif obj_id == ID.PurchasePresentDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["presents"] = parse_obj(data)
		obj["message"] = parseUTF(data)
		return ("PurchasePresentDef", obj)

	elif obj_id == ID.PurchasePresentItemDef:
		obj = {}
		obj["price"] = unpackex("i", data)
		obj["message"] = parseUTF(data)
		obj["items"] = parse_obj(data)
		return ("PurchasePresentItemDef", obj)

	elif obj_id == ID.QnqConstants:
		obj = {}
		return ("QnqConstants", obj)

	elif obj_id == ID.QnqServletConstants:
		obj = {}
		return ("QnqServletConstants", obj)

	elif obj_id == ID.QuestionDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["question"] = parseUTF(data)
		obj["questionVoiceId"] = unpackex("i", data)
		obj["params"] = parse_obj(data)
		return ("QuestionDef", obj)

	elif obj_id == ID.QuestionInfo:
		obj = {}
		obj["encodedUid"] = unpackex("i", data)
		obj["avatar"] = unpackex("i", data)
		obj["friendName"] = parseUTF(data)
		obj["questionId"] = unpackex("i", data)
		obj["choiceIndex"] = unpackex("i", data)
		obj["snsProfileImage"] = parse_obj(data)
		obj["snsType"] = unpackex("b", data)
		return ("QuestionInfo", obj)

	elif obj_id == ID.QuestionParam:
		obj = {}
		obj["choice"] = parseUTF(data)
		obj["message"] = parseUTF(data)
		obj["messageVoiceId"] = unpackex("i", data)
		return ("QuestionParam", obj)

	elif obj_id == ID.RankingContentDef:
		obj = {}
		obj["type"] = unpackex("i", data)
		obj["argi"] = unpackex("i", data)
		obj["rewardId"] = unpackex("i", data)
		obj["daily"] = unpackex("b", data)
		obj["guild"] = unpackex("b", data)
		obj["deliverTableId"] = unpackex("i", data)
		obj["deliverPtsPercentMap"] = parse_primitive_obj(ID(7), data)
		return ("RankingContentDef", obj)

	elif obj_id == ID.RankingDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["title"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["storyComicId"] = unpackex("i", data)
		obj["howtoComicId"] = unpackex("i", data)
		obj["content"] = parse_obj(data)
		obj["groupType"] = unpackex("i", data)
		obj["groupIdIndexMap"] = parse_primitive_obj(ID(7), data)
		obj["hasDefaultGroupContent"] = unpackex("b", data)
		obj["rankTextColor"] = unpackex("i", data)
		obj["pointTextColor"] = unpackex("i", data)
		obj["balloonTextColor"] = unpackex("i", data)
		obj["rewardTextColor"] = unpackex("i", data)
		obj["rankingTitleTextColor"] = unpackex("i", data)
		obj["topRecordMatColor"] = unpackex("i", data)
		obj["rankingRewardMatColor"] = unpackex("i", data)
		obj["pointRewardMatColor"] = unpackex("i", data)
		obj["levelRewardMatColor"] = unpackex("i", data)
		obj["topRecordBgMatColor"] = unpackex("i", data)
		obj["rankingRewardBgMatColor"] = unpackex("i", data)
		obj["pointRewardBgMatColor"] = unpackex("i", data)
		obj["levelRewardBgMatColor"] = unpackex("i", data)
		obj["recordMatColor"] = unpackex("i", data)
		obj["rankingRewardLineColor"] = unpackex("i", data)
		obj["pointRewardLineColor"] = unpackex("i", data)
		obj["levelRewardLineColor"] = unpackex("i", data)
		return ("RankingDef", obj)

	elif obj_id == ID.RankingInfo:
		obj = {}
		obj["contentIndex"] = unpackex("i", data)
		obj["type"] = unpackex("i", data)
		obj["contentTitle"] = parseUTF(data)
		obj["argi"] = unpackex("i", data)
		obj["showOnly"] = unpackex("b", data)
		obj["guild"] = unpackex("b", data)
		obj["desc"] = parseUTF(data)
		obj["myPoint"] = unpackex("i", data)
		obj["myRoughPlace"] = unpackex("i", data)
		obj["topRecords"] = parse_obj(data)
		obj["rewardId"] = unpackex("i", data)
		obj["rewardPlaceAndPoint"] = parse_obj(data)
		obj["topRecordSizeMax"] = unpackex("i", data)
		obj["totalPoint"] = unpackex("i", data)
		return ("RankingInfo", obj)

	elif obj_id == ID.RankingRecord:
		obj = {}
		obj["point"] = unpackex("i", data)
		obj["encodeUid"] = unpackex("i", data)
		obj["playerName"] = parseUTF(data)
		obj["avatar"] = unpackex("i", data)
		obj["snsType"] = unpackex("i", data)
		obj["snsProfileImage"] = parse_obj(data)
		return ("RankingRecord", obj)

	elif obj_id == ID.RankingRewardDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rewardIdTable"] = parse_obj(data)
		obj["rankingRewards"] = parse_obj(data)
		obj["pointRewards"] = parse_obj(data)
		obj["globalRewards"] = parse_obj(data)
		return ("RankingRewardDef", obj)

	elif obj_id == ID.RankingRewardItemDef:
		obj = {}
		obj["sortedIndex"] = unpackex("i", data)
		obj["last"] = unpackex("b", data)
		obj["argi"] = unpackex("i", data)
		obj["screeningItems"] = parse_obj(data)
		return ("RankingRewardItemDef", obj)

	elif obj_id == ID.RecipeNoteData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["visible"] = unpackex("b", data)
		obj["available"] = unpackex("b", data)
		obj["purchased"] = unpackex("b", data)
		obj["targetValue"] = unpackex("i", data)
		obj["currentValue"] = unpackex("i", data)
		return ("RecipeNoteData", obj)

	elif obj_id == ID.RecipeNoteDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["kitchenwareId"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["minutes"] = unpackex("i", data)
		obj["premises"] = parse_obj(data)
		obj["conditionDesc"] = parseUTF(data)
		obj["eventId"] = unpackex("i", data)
		obj["price"] = unpackex("i", data)
		obj["defaults"] = parse_obj(data)
		obj["appends"] = parse_obj(data)
		obj["happeningIds"] = parse_obj(data)
		obj["failureIds"] = parse_obj(data)
		obj["hasBonusPrize"] = unpackex("b", data)
		obj["targetType"] = unpackex("i", data)
		obj["targetId"] = unpackex("i", data)
		return ("RecipeNoteDef", obj)

	elif obj_id == ID.RuleDef:
		obj = {}
		obj["focusGainedLimitTimeMinites"] = unpackex("b", data)
		obj["reloadFollowerTime"] = unpackex("i", data)
		obj["ruleFlags"] = parse_obj(data)
		obj["roundingFollowPastDay"] = unpackex("b", data)
		obj["locale"] = parseUTF(data)
		obj["localeCode"] = parse_obj(data)
		obj["titleMusic"] = unpackex("i", data)
		obj["heavenTimeSecs"] = unpackex("i", data)
		obj["touchRewards"] = parse_obj(data)
		obj["carnaviIds"] = parse_obj(data)
		obj["enabledMoneyShop"] = unpackex("b", data)
		obj["menuItems"] = parse_obj(data)
		obj["shopItems"] = parse_obj(data)
		obj["collectionTypes"] = parse_obj(data)
		obj["hurryUpReduceMinutesPerMetal"] = unpackex("i", data)
		obj["hurryUpMetalBase"] = unpackex("i", data)
		obj["cookingTooMatchTimeHours"] = unpackex("i", data)
		obj["lowerLimitPercentForRouletteSpeed"] = unpackex("i", data)
		obj["hurryUpItemBaseMap"] = parse_primitive_obj(ID(7), data)
		obj["hurryUpReduceMinutesPerItem"] = parse_primitive_obj(ID(7), data)
		obj["gachaRateScreeningLevel"] = unpackex("i", data)
		obj["missionCommentAchievePercent"] = parse_obj(data)
		obj["maxFriendsExtension"] = unpackex("h", data)
		obj["friendsExtensionValue"] = unpackex("h", data)
		obj["friendsExtensionPrices"] = parse_obj(data)
		obj["updateFollowerTime"] = unpackex("i", data)
		obj["maximumFriendPresentForGPWhileEvent"] = unpackex("i", data)
		obj["friendlyValueByAssist"] = unpackex("i", data)
		obj["gudetamaTeamIds"] = parse_obj(data)
		obj["minimumMessageTime"] = unpackex("i", data)
		obj["messagePercents"] = parse_obj(data)
		obj["messageResetHourOffset"] = unpackex("i", data)
		obj["friendPresentCost"] = unpackex("i", data)
		obj["friendPresentGp"] = unpackex("i", data)
		obj["friendPresentGpCountPerDay"] = unpackex("i", data)
		obj["friendPresentGpGlobalCountPerDay"] = unpackex("i", data)
		obj["freeFriendPresentCountPerDay"] = unpackex("i", data)
		obj["placeArGudetamaNumTable"] = parse_obj(data)
		obj["placeArStampNumTable"] = parse_obj(data)
		obj["placeHomeStampNumTable"] = parse_obj(data)
		obj["numScreeningPresentLogs"] = unpackex("i", data)
		obj["maxFriendPresentMoneyPerRank"] = unpackex("i", data)
		obj["maxAssistPerDay"] = unpackex("i", data)
		obj["defStampSpainPath"] = parseUTF(data)
		obj["imobileAndroidPlacement"] = parse_obj(data)
		obj["imobileIOSPlacement"] = parse_obj(data)
		obj["fiveAdsAndroidId"] = parseUTF(data)
		obj["fiveAdsIOSId"] = parseUTF(data)
		obj["fiveAdsAndroidSlotId"] = parse_obj(data)
		obj["fiveAdsIOSSlotId"] = parse_obj(data)
		obj["nendAdsAndroidIds"] = parse_obj(data)
		obj["nendAdsIOSIds"] = parse_obj(data)
		obj["eventBannerUpdateTime"] = unpackex("i", data)
		obj["bannerCircleSec"] = unpackex("i", data)
		obj["bannerCircle"] = unpackex("b", data)
		obj["disableBannerOSVersionMap"] = parse_primitive_obj(ID(8), data)
		obj["maioAdsAndroidId"] = parseUTF(data)
		obj["maioAdsIOSId"] = parseUTF(data)
		obj["maioAdsZoneAndroidId"] = parseUTF(data)
		obj["maioAdsZoneIOSId"] = parseUTF(data)
		obj["videoTraceErrorSec"] = unpackex("i", data)
		obj["tapjoyAdsAndroidId"] = parse_obj(data)
		obj["tapjoyAdsIOSId"] = parse_obj(data)
		obj["vangleAdsAndroidId"] = parseUTF(data)
		obj["vangleAdsIOSId"] = parseUTF(data)
		obj["vangleAdsAndroidPlacementIds"] = parse_obj(data)
		obj["vangleAdsIOSPlacementIds"] = parse_obj(data)
		obj["ironsourceAdsAndroidId"] = parseUTF(data)
		obj["ironsourceAdsIOSId"] = parseUTF(data)
		obj["ironSourceGlobalAdsAndroidId"] = parseUTF(data)
		obj["ironSourceGlobalAdsIOSId"] = parseUTF(data)
		obj["admobBannerAndroidId"] = parseUTF(data)
		obj["admobBannerIOSId"] = parseUTF(data)
		obj["admobVideoAndroidId"] = parseUTF(data)
		obj["admobVideoIOSId"] = parseUTF(data)
		obj["nendAndroidIds"] = parse_obj(data)
		obj["nendIOSIds"] = parse_obj(data)
		obj["chartboosVideoAndroidIds"] = parse_obj(data)
		obj["chartboosVideoIOSIds"] = parse_obj(data)
		obj["promotionVideoNames"] = parse_obj(data)
		obj["promotionVideoIdAndRatio"] = parse_obj(data)
		obj["priorityMaxVideoCount"] = unpackex("i", data)
		obj["preLoadingVideoSecs"] = unpackex("i", data)
		obj["videoLodingIntervalMillisec"] = unpackex("i", data)
		obj["videoGlobalLodingIntervalMillisec"] = unpackex("i", data)
		obj["videoInitGiveupMilliSec"] = unpackex("i", data)
		obj["imobileInterstitialAndroidPlacement"] = parse_obj(data)
		obj["imobileInterstitialIOSPlacement"] = parse_obj(data)
		obj["nendInterstitialAndroid"] = parse_obj(data)
		obj["nendInterstitialIOS"] = parse_obj(data)
		obj["interstitiaIntervalSecs"] = unpackex("i", data)
		obj["interstitiaIntervalGlobalSecs"] = unpackex("i", data)
		obj["ironVideoPlacementAndroidId"] = parse_obj(data)
		obj["ironVideoPlacementIOSId"] = parse_obj(data)
		obj["ironOfferPlacementAndroidId"] = parse_obj(data)
		obj["ironOfferPlacementIOSId"] = parse_obj(data)
		obj["ironInterPlacementAndroidId"] = parse_obj(data)
		obj["ironInterPlacementIOSId"] = parse_obj(data)
		obj["twitter_Key"] = parseUTF(data)
		obj["twitter_Secret"] = parseUTF(data)
		obj["facebook_Key"] = parseUTF(data)
		obj["useSnsTwitter"] = unpackex("b", data)
		obj["useSnsFacebook"] = unpackex("b", data)
		obj["tiwtterSchemeAndroidURL"] = parseUTF(data)
		obj["tiwtterSchemeIOSURL"] = parseUTF(data)
		obj["snsLinkBonusNum"] = unpackex("b", data)
		obj["usefulShopShortcut"] = unpackex("b", data)
		obj["presentDeliverPtsPercent"] = unpackex("i", data)
		obj["snsShareBonusType"] = unpackex("i", data)
		obj["cupGachaOpenMinPerTier"] = unpackex("i", data)
		obj["cupGachaOpenMetalPerTier"] = unpackex("i", data)
		obj["cupGachaShortMinByAd"] = unpackex("b", data)
		obj["cupGachaShortNumByAd"] = unpackex("b", data)
		obj["cupGachaMailKeepDay"] = unpackex("h", data)
		obj["useHomeDecoEachType"] = unpackex("b", data)
		obj["cookingShortCut"] = unpackex("b", data)
		obj["memoryCookingRecipe"] = unpackex("b", data)
		obj["frameIds"] = parse_obj(data)
		obj["titleName"] = parseUTF(data)
		obj["titleSpineName"] = parseUTF(data)
		obj["titleGudetamaSpineName"] = parseUTF(data)
		obj["duplicateSceneCheckClasses"] = parse_obj(data)
		obj["titleNameCountry"] = parse_primitive_obj(ID(8), data)
		obj["titleSpineNameCountry"] = parse_primitive_obj(ID(8), data)
		obj["titleGudetamaSpineNameCountry"] = parse_primitive_obj(ID(8), data)
		return ("RuleDef", obj)

	elif obj_id == ID.ScreeningDef:
		obj = {}
		obj["flags"] = parse_obj(data)
		return ("ScreeningDef", obj)

	elif obj_id == ID.ScreeningGachaItemParam:
		obj = {}
		obj["item"] = parse_obj(data)
		obj["newFlag"] = unpackex("b", data)
		obj["pickupFlag"] = unpackex("b", data)
		obj["rate"] = unpackex("i", data)
		return ("ScreeningGachaItemParam", obj)

	elif obj_id == ID.SequenceTable:
		obj = {}
		obj["offset"] = unpackex("f", data)
		obj["rate"] = unpackex("f", data)
		obj["indexOffset"] = unpackex("i", data)
		obj["values"] = parse_obj(data)
		return ("SequenceTable", obj)

	elif obj_id == ID.SetItemAlternativeParam:
		obj = {}
		obj["rsrc"] = unpackex("i", data)
		obj["items"] = parse_obj(data)
		return ("SetItemAlternativeParam", obj)

	elif obj_id == ID.SetItemBuyData:
		obj = {}
		obj["count"] = unpackex("h", data)
		return ("SetItemBuyData", obj)

	elif obj_id == ID.SetItemDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["viewType"] = unpackex("b", data)
		obj["items"] = parse_obj(data)
		obj["startTimeSec"] = unpackex("i", data)
		obj["endTimeSec"] = unpackex("i", data)
		obj["chargeItem"] = parse_obj(data)
		obj["buyableCount"] = unpackex("h", data)
		obj["rsrc"] = unpackex("i", data)
		obj["alternativeParam"] = parse_obj(data)
		return ("SetItemDef", obj)

	elif obj_id == ID.ShareBonusDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["item"] = parse_obj(data)
		obj["message"] = parseUTF(data)
		obj["alternativeMessage"] = parseUTF(data)
		return ("ShareBonusDef", obj)

	elif obj_id == ID.StampData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["num"] = unpackex("i", data)
		obj["available"] = unpackex("b", data)
		return ("StampData", obj)

	elif obj_id == ID.StampDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["privately"] = unpackex("b", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["conditionDesc"] = parseUTF(data)
		obj["price"] = parse_obj(data)
		obj["isNew"] = unpackex("b", data)
		obj["rare"] = unpackex("i", data)
		obj["isSpine"] = unpackex("b", data)
		obj["homeStampSettingId"] = unpackex("i", data)
		return ("StampDef", obj)

	elif obj_id == ID.StampInfo:
		obj = {}
		obj["updateStamps"] = parse_obj(data)
		obj["removeStampIds"] = parse_obj(data)
		return ("StampInfo", obj)

	elif obj_id == ID.SubHomeStampSettingDef:
		obj = {}
		obj["animationName"] = parseUTF(data)
		obj["loop"] = unpackex("b", data)
		obj["music"] = parseUTF(data)
		obj["sound"] = parseUTF(data)
		obj["voiceId"] = unpackex("i", data)
		return ("SubHomeStampSettingDef", obj)

	elif obj_id == ID.SystemMailData:
		obj = {}
		obj["type"] = unpackex("b", data)
		obj["kind"] = unpackex("b", data)
		obj["senderEncodedUid"] = unpackex("i", data)
		obj["item"] = parse_obj(data)
		obj["title"] = parseUTF(data)
		obj["url"] = parseUTF(data)
		obj["urlAndroid"] = parseUTF(data)
		obj["alreadyRead"] = unpackex("b", data)
		obj["noticeIconId"] = unpackex("i", data)
		obj["deleteSec"] = unpackex("i", data)
		obj["manualDeletion"] = unpackex("b", data)
		obj["uniqueKey"] = unpackex("i", data)
		obj["message"] = parseUTF(data)
		obj["receivedSecs"] = unpackex("i", data)
		return ("SystemMailData", obj)

	elif obj_id == ID.TouchDef:
		obj = {}
		obj["voiceEvents"] = parse_obj(data)
		obj["itemEvents"] = parse_obj(data)
		obj["randomVoiceIds"] = parse_obj(data)
		return ("TouchDef", obj)

	elif obj_id == ID.TouchEventDef:
		obj = {}
		obj["voice"] = unpackex("i", data)
		return ("TouchEventDef", obj)

	elif obj_id == ID.TouchEventParam:
		obj = {}
		obj["touchNum"] = unpackex("i", data)
		obj["event"] = unpackex("i", data)
		obj["voice"] = unpackex("i", data)
		obj["paramByte"] = unpackex("b", data)
		return ("TouchEventParam", obj)

	elif obj_id == ID.TouchInfo:
		obj = {}
		obj["params"] = parse_obj(data)
		obj["bonusRange"] = parse_obj(data)
		return ("TouchInfo", obj)

	elif obj_id == ID.UsefulData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["num"] = unpackex("i", data)
		obj["available"] = unpackex("b", data)
		obj["nextAvailablePurchaseSec"] = unpackex("i", data)
		return ("UsefulData", obj)

	elif obj_id == ID.UsefulDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["privately"] = unpackex("b", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["usable"] = unpackex("i", data)
		obj["event"] = unpackex("b", data)
		obj["abilities"] = parse_obj(data)
		obj["assistAbilities"] = parse_obj(data)
		obj["friendlyValue"] = unpackex("i", data)
		obj["conditionDesc"] = parseUTF(data)
		obj["sortIndex"] = unpackex("i", data)
		obj["price"] = parse_obj(data)
		obj["isNew"] = unpackex("b", data)
		obj["eventId"] = unpackex("i", data)
		obj["kitchenwareTypes"] = parse_obj(data)
		obj["possessionLimit"] = unpackex("i", data)
		obj["purchaseResetHourOffset"] = unpackex("b", data)
		return ("UsefulDef", obj)

	elif obj_id == ID.UsefulInfo:
		obj = {}
		obj["updateUsefuls"] = parse_obj(data)
		obj["removeUsefulIds"] = parse_obj(data)
		return ("UsefulInfo", obj)

	elif obj_id == ID.UserAbilityData:
		obj = {}
		obj["ability"] = parse_obj(data)
		obj["restTimeSecs"] = unpackex("i", data)
		return ("UserAbilityData", obj)

	elif obj_id == ID.UserAssistData:
		obj = {}
		obj["num"] = unpackex("i", data)
		return ("UserAssistData", obj)

	elif obj_id == ID.UserData:
		obj = {}
		obj["uid"] = unpackex("i", data)
		obj["encodedUid"] = unpackex("i", data)
		obj["playerName"] = parseUTF(data)
		obj["gender"] = unpackex("i", data)
		obj["doneFirstLogin"] = unpackex("b", data)
		obj["pushFlags"] = unpackex("i", data)
		obj["nextDailyPresentTime"] = unpackex("d", data)
		obj["timeZoneOffset"] = unpackex("i", data)
		obj["noticeFlagData"] = parse_obj(data)
		obj["locale"] = parseUTF(data)
		obj["rank"] = unpackex("i", data)
		obj["chargeMetal"] = unpackex("i", data)
		obj["freeMetal"] = unpackex("i", data)
		obj["subMetal"] = unpackex("i", data)
		obj["chargeMoney"] = unpackex("i", data)
		obj["freeMoney"] = unpackex("i", data)
		obj["avatar"] = unpackex("i", data)
		obj["avatarMap"] = parse_primitive_obj(ID(7), data)
		obj["area"] = unpackex("i", data)
		obj["comment"] = unpackex("h", data)
		obj["placedGudetamaId"] = unpackex("i", data)
		obj["kitchenwareMap"] = parse_primitive_obj(ID(7), data)
		obj["recipeNoteMap"] = parse_primitive_obj(ID(7), data)
		obj["gudetamaMap"] = parse_primitive_obj(ID(7), data)
		obj["gachaMap"] = parse_primitive_obj(ID(7), data)
		obj["friendPresentMoneyParamMap"] = parse_primitive_obj(ID(7), data)
		obj["stampMap"] = parse_primitive_obj(ID(7), data)
		obj["usefulMap"] = parse_primitive_obj(ID(7), data)
		obj["utensilMap"] = parse_primitive_obj(ID(7), data)
		obj["decorationMap"] = parse_primitive_obj(ID(7), data)
		obj["decorationId"] = unpackex("i", data)
		obj["wantedGudetamas"] = parse_obj(data)
		obj["maxDelusion"] = unpackex("i", data)
		obj["delusionStartTimeSecs"] = unpackex("i", data)
		obj["touchInfo"] = parse_obj(data)
		obj["dropItemEvent"] = parse_obj(data)
		obj["heavenEvent"] = parse_obj(data)
		obj["userAbilities"] = parse_obj(data)
		obj["features"] = parse_obj(data)
		obj["numAcquiredVideoAdReward"] = unpackex("i", data)
		obj["videoAdRewardUpdateTimeSecs"] = unpackex("i", data)
		obj["linkageMap"] = parse_primitive_obj(ID(7), data)
		obj["numPurchaseMap"] = parse_primitive_obj(ID(7), data)
		obj["numFriendsExtension"] = unpackex("i", data)
		obj["snsInterlockType"] = unpackex("b", data)
		obj["snsTwitterUid"] = parseUTF(data)
		obj["snsFacebookUid"] = parseUTF(data)
		obj["purchasePresentMap"] = parse_primitive_obj(ID(7), data)
		obj["placeGudetamaExpansionCount"] = unpackex("h", data)
		obj["placeStampExpansionCount"] = unpackex("h", data)
		obj["commentList"] = parse_primitive_obj(ID(9), data)
		obj["finishMonthlyPremiumBonusTimeSec"] = unpackex("i", data)
		obj["noticeMonthlyPremiumBonusTimeSec"] = unpackex("i", data)
		obj["sendTouchCount"] = unpackex("i", data)
		obj["numAcquiredIdentifiedPresentMap"] = parse_primitive_obj(ID(7), data)
		obj["setItemBuyMap"] = parse_primitive_obj(ID(7), data)
		obj["numFriendPresentForGPWhileEventMap"] = parse_primitive_obj(ID(7), data)
		obj["cupGachaData"] = parse_obj(data)
		obj["cupGachaConditionClearIds"] = parse_primitive_obj(ID(9), data)
		obj["homeDecoDataMap"] = parse_primitive_obj(ID(7), data)
		obj["placeHomeStampExpansionCount"] = unpackex("h", data)
		return ("UserData", obj)

	elif obj_id == ID.UserGachaData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["playCount"] = unpackex("i", data)
		obj["prices"] = parse_obj(data)
		obj["onceMorePlayCount"] = unpackex("b", data)
		obj["freePlayCount"] = unpackex("b", data)
		return ("UserGachaData", obj)

	elif obj_id == ID.UserGachaPriceData:
		obj = {}
		obj["dailyPlayCount"] = unpackex("i", data)
		return ("UserGachaPriceData", obj)

	elif obj_id == ID.UserPresentMoneyData:
		obj = {}
		obj["pid"] = unpackex("d", data)
		obj["encodedUid"] = unpackex("i", data)
		obj["playerName"] = parseUTF(data)
		obj["playerRank"] = unpackex("i", data)
		obj["money"] = unpackex("i", data)
		obj["presentTimeSecs"] = unpackex("i", data)
		obj["avatar"] = unpackex("i", data)
		obj["snsProfileImage"] = parse_obj(data)
		obj["snsType"] = unpackex("b", data)
		return ("UserPresentMoneyData", obj)

	elif obj_id == ID.UserProfileData:
		obj = {}
		obj["encodedUid"] = unpackex("i", data)
		obj["playerName"] = parseUTF(data)
		obj["playerRank"] = unpackex("i", data)
		obj["avatar"] = unpackex("i", data)
		obj["gender"] = unpackex("i", data)
		obj["area"] = unpackex("i", data)
		obj["comment"] = unpackex("i", data)
		obj["followState"] = unpackex("b", data)
		obj["followRequestSecs"] = unpackex("i", data)
		obj["snsProfileImage"] = parse_obj(data)
		obj["lastActiveSec"] = unpackex("i", data)
		obj["snsId"] = parseUTF(data)
		obj["snsType"] = unpackex("b", data)
		return ("UserProfileData", obj)

	elif obj_id == ID.UserRankingData:
		obj = {}
		obj["rankingPoint"] = unpackex("i", data)
		return ("UserRankingData", obj)

	elif obj_id == ID.UserRoomInfo:
		obj = {}
		obj["placedGudetamaId"] = unpackex("i", data)
		obj["questionId"] = unpackex("i", data)
		obj["kitchenwareMap"] = parse_primitive_obj(ID(7), data)
		obj["friendlyData"] = parse_obj(data)
		obj["lastFriendlyLevel"] = unpackex("i", data)
		obj["friendPresentMoneyParam"] = parse_obj(data)
		obj["assistData"] = parse_obj(data)
		obj["decorationId"] = unpackex("i", data)
		obj["homeDecoDataList"] = parse_primitive_obj(ID(9), data)
		return ("UserRoomInfo", obj)

	elif obj_id == ID.UserWantedData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["updateTime"] = unpackex("i", data)
		return ("UserWantedData", obj)

	elif obj_id == ID.UtensilData:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["acquired"] = unpackex("b", data)
		obj["available"] = unpackex("b", data)
		return ("UtensilData", obj)

	elif obj_id == ID.UtensilDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["desc"] = parseUTF(data)
		obj["conditionDesc"] = parseUTF(data)
		obj["price"] = parse_obj(data)
		obj["isNew"] = unpackex("b", data)
		return ("UtensilDef", obj)

	elif obj_id == ID.UtensilInfo:
		obj = {}
		obj["updateUtensils"] = parse_obj(data)
		obj["removeUtensilIds"] = parse_obj(data)
		return ("UtensilInfo", obj)

	elif obj_id == ID.VideoAdRewardDef:
		obj = {}
		obj["items"] = parse_obj(data)
		return ("VideoAdRewardDef", obj)

	elif obj_id == ID.VoiceDef:
		obj = {}
		obj["id"] = unpackex("i", data)
		obj["rsrc"] = unpackex("i", data)
		obj["gudetamaId"] = unpackex("i", data)
		obj["type"] = unpackex("b", data)
		obj["number"] = unpackex("i", data)
		obj["name"] = parseUTF(data)
		obj["position"] = unpackex("i", data)
		obj["offset"] = parse_obj(data)
		obj["params"] = parse_obj(data)
		return ("VoiceDef", obj)

	elif obj_id == ID.VoiceParam:
		obj = {}
		obj["resources"] = parse_obj(data)
		obj["names"] = parse_obj(data)
		obj["delays"] = parse_obj(data)
		obj["positions"] = parse_obj(data)
		obj["offsets"] = parse_obj(data)
		return ("VoiceParam", obj)

	elif obj_id == ID.AbilityParam:
		obj = {}
		obj["type"] = unpackex("i", data)
		obj["values"] = parse_obj(data)
		obj["secs"] = unpackex("i", data)
		return ("AbilityParam", obj)

	elif obj_id == ID.UserProfileData:
		obj = {}
		obj["encodedUid"] = unpackex("i", data)
		obj["playerName"] = parseUTF(data)
		obj["playerRank"] = unpackex("i", data)
		obj["avatar"] = unpackex("i", data)
		obj["gender"] = unpackex("i", data)
		obj["area"] = unpackex("i", data)
		obj["comment"] = unpackex("i", data)
		obj["followState"] = unpackex("b", data)
		obj["followRequestSecs"] = unpackex("i", data)
		obj["snsProfileImage"] = parse_obj(data)
		obj["lastActiveSec"] = unpackex("i", data)
		obj["snsId"] = parseUTF(data)
		obj["snsType"] = unpackex("b", data)
		return ("UserProfileData", obj)
